/**
 * Builds apps/app.roadtrip/states.js from us-atlas (US Census boundaries, ISC license).
 *
 *   npm i us-atlas@3 topojson-client@3 topojson-simplify@3 d3-geo@3
 *   node tools/build-states.js
 *
 * Borders are simplified on the shared topology, so neighbors keep identical edges
 * (simplifying each state on its own makes neighbors overlap near rivers).
 *
 * Output per state: abbreviation, name, bounding box, simplified lon/lat rings (for GPS lookup)
 * and pre-projected screen rings (for drawing, Albers USA with Alaska/Hawaii insets).
 */

var path = require('path');
var fs = require('fs');
var topo = require('topojson-client');
var topoSimplify = require('topojson-simplify');
var d3 = require('d3-geo');
var atlas = require('us-atlas/states-10m.json');

var ABBR = {
    'Alabama': 'AL', 'Alaska': 'AK', 'Arizona': 'AZ', 'Arkansas': 'AR', 'California': 'CA', 'Colorado': 'CO',
    'Connecticut': 'CT', 'Delaware': 'DE', 'District of Columbia': 'DC', 'Florida': 'FL', 'Georgia': 'GA',
    'Hawaii': 'HI', 'Idaho': 'ID', 'Illinois': 'IL', 'Indiana': 'IN', 'Iowa': 'IA', 'Kansas': 'KS',
    'Kentucky': 'KY', 'Louisiana': 'LA', 'Maine': 'ME', 'Maryland': 'MD', 'Massachusetts': 'MA',
    'Michigan': 'MI', 'Minnesota': 'MN', 'Mississippi': 'MS', 'Missouri': 'MO', 'Montana': 'MT',
    'Nebraska': 'NE', 'Nevada': 'NV', 'New Hampshire': 'NH', 'New Jersey': 'NJ', 'New Mexico': 'NM',
    'New York': 'NY', 'North Carolina': 'NC', 'North Dakota': 'ND', 'Ohio': 'OH', 'Oklahoma': 'OK',
    'Oregon': 'OR', 'Pennsylvania': 'PA', 'Rhode Island': 'RI', 'South Carolina': 'SC', 'South Dakota': 'SD',
    'Tennessee': 'TN', 'Texas': 'TX', 'Utah': 'UT', 'Vermont': 'VT', 'Virginia': 'VA', 'Washington': 'WA',
    'West Virginia': 'WV', 'Wisconsin': 'WI', 'Wyoming': 'WY'
};

var MAP_W = 780, MAP_H = 300;
var LOOKUP_WEIGHT = 0.004;     // min triangle area (deg²) kept for GPS lookup; passes 35 border-city tests
var DRAW_WEIGHT = 0.004;       // coarser for drawing
var MIN_ISLAND_DEG = 0.15;     // drop small islands from lookup...
var MIN_ISLAND_PX = 3;         // ...and from the drawing

function simplified(weight) {
    var t = topoSimplify.presimplify(JSON.parse(JSON.stringify(atlas)), topoSimplify.planarTriangleArea);
    t = topoSimplify.simplify(t, weight);
    var byName = {};
    topo.feature(t, t.objects.states).features.forEach(function(f) { byName[f.properties.name] = f; });
    return byName;
}

function polygons(f) {
    return f.geometry.type === 'Polygon' ? [f.geometry.coordinates] : f.geometry.coordinates;
}

function span(ring) {
    var x0 = Infinity, y0 = Infinity, x1 = -Infinity, y1 = -Infinity;
    ring.forEach(function(p) { x0 = Math.min(x0, p[0]); y0 = Math.min(y0, p[1]); x1 = Math.max(x1, p[0]); y1 = Math.max(y1, p[1]); });
    return Math.max(x1 - x0, y1 - y0);
}

function flat(ring, digits) {
    var f = Math.pow(10, digits), out = [];
    ring.forEach(function(p) { out.push(Math.round(p[0] * f) / f, Math.round(p[1] * f) / f); });
    return out;
}

var fc = topo.feature(atlas, atlas.objects.states);
var projection = d3.geoAlbersUsa().fitSize([MAP_W, MAP_H], fc);
var lookupShapes = simplified(LOOKUP_WEIGHT);
var drawShapes = simplified(DRAW_WEIGHT);

var states = [];
fc.features.forEach(function(f) {
    var name = f.properties.name, abbr = ABBR[name];
    if (!abbr) return;  // skip territories

    var geo = [], scr = [];
    var lp = polygons(lookupShapes[name]);
    lp.forEach(function(poly) {
        var outer = poly[0];  // holes ignored: none matter at this scale
        if (outer.length >= 4 && (lp.length === 1 || span(outer) >= MIN_ISLAND_DEG)) geo.push(flat(outer, 3));
    });
    var dp = polygons(drawShapes[name]);
    dp.forEach(function(poly) {
        var projected = poly[0].map(projection).filter(Boolean);
        if (projected.length >= 3 && (dp.length === 1 || span(projected) >= MIN_ISLAND_PX)) scr.push(flat(projected, 0));
    });

    var b = d3.geoBounds(f);
    if (b[0][0] > b[1][0]) { b[0][0] = -180; b[1][0] = 180; }  // Alaska crosses the 180th meridian
    states.push({a: abbr, n: name, b: [b[0][0], b[0][1], b[1][0], b[1][1]].map(function(v) {
        return Math.round(v * 100) / 100;
    }), g: geo, s: scr});
});

states.sort(function(x, y) { return x.a < y.a ? -1 : 1; });

var out = '/* Generated by tools/build-states.js from us-atlas (US Census Bureau data). Do not edit. */\n' +
    'var ROADTRIP_MAP = {w: ' + MAP_W + ', h: ' + MAP_H + '};\n' +
    'var ROADTRIP_STATES = ' + JSON.stringify(states) + ';\n';

var file = path.join(__dirname, '..', 'apps', 'app.roadtrip', 'states.js');
fs.mkdirSync(path.dirname(file), {recursive: true});
fs.writeFileSync(file, out);
console.log(states.length + ' states, ' + Math.round(out.length / 1024) + ' KB -> ' + file);
